version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nishanth81799
      MYSQL_DATABASE: aquatrack
      MYSQL_USER: aquatrack_user
      MYSQL_PASSWORD: aquatrack_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # AquaTrack Application
  app:
    build: .
    restart: unless-stopped
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://aquatrack_user:aquatrack_pass@db:3306/aquatrack
      - NEXTAUTH_SECRET=your-secret-key-change-this
      - NEXTAUTH_URL=http://localhost:9002
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npm run start
      "

volumes:
  db_data:
