version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nishanth81799
      MYSQL_DATABASE: aquatrack
      MYSQL_USER: aquatrack_user
      MYSQL_PASSWORD: aquatrack_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # AquaTrack Application - Development Mode (no build required)
  app:
    image: node:18-alpine
    restart: unless-stopped
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://aquatrack_user:aquatrack_pass@db:3306/aquatrack
      - NEXTAUTH_SECRET=your-secret-key-change-this
      - NEXTAUTH_URL=http://localhost:9002
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "
        echo 'Installing dependencies locally...' &&
        npm install --prefer-offline --no-audit --progress=false &&
        echo 'Generating Prisma client...' &&
        npx prisma generate &&
        echo 'Pushing database schema...' &&
        npx prisma db push &&
        echo 'Starting development server...' &&
        npm run dev
      "

volumes:
  db_data: